# Customer & Sales Analysis — SQL

## Project Objective

This project analyzes customer and sales data using SQL to uncover
business insights across customers, products, regions, and monthly sales.

The analysis focuses on identifying:
- Top-performing customers
- Customer purchasing behavior
- High-value customer segments
- Product performance
- Regional revenue performance
- Monthly revenue trends
- Business growth opportunities

## Tools Used

- SQL
- SQLite
- Python
- Pandas
- Google Colab

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")

In [ ]:
conn.execute("""
CREATE TABLE customers (
    customer_id INTEGER,
        customer_name TEXT,
            region TEXT
            )
            """)

In [ ]:
conn.executemany("""
INSERT INTO customers (customer_id, customer_name, region)
VALUES (?, ?, ?)
""", [
    (1, "Ada", "Ibadan"),
        (2, "Bola", "Lagos"),
            (3, "Chinedu", "Osogbo"),
                (4, "Emeka", "Ibadan"),
                    (5, "Fatima", "Lagos")
                    ])

In [ ]:
pd.read_sql_query("""
SELECT *
FROM customers;
""", conn)

   customer_id customer_name  region
0            1           Ada  Ibadan
1            2          Bola   Lagos
2            3       Chinedu  Osogbo
3            4         Emeka  Ibadan
4            5        Fatima   Lagos

In [ ]:
conn.execute("""
CREATE TABLE orders (
    order_id INTEGER,
        customer_id INTEGER,
            product TEXT,
                order_date TEXT,
                    revenue INTEGER
                    )
                    """)

In [ ]:
conn.executemany("""
INSERT INTO orders (order_id, customer_id, product, order_date, revenue)
VALUES (?, ?, ?, ?, ?)
""", [
    (1001, 1, "Rice",  "2026-01-05", 50000),
        (1002, 2, "Beans", "2026-01-07", 30000),
            (1003, 1, "Oil",   "2026-01-12", 80000),
                (1004, 3, "Rice",  "2026-01-18", 70000),
                    (1005, 2, "Rice",  "2026-01-22", 60000),
                        (1006, 4, "Beans", "2026-02-03", 90000),
                            (1007, 5, "Oil",   "2026-02-08", 40000),
                                (1008, 1, "Rice",  "2026-02-14", 100000),
                                    (1009, 3, "Beans", "2026-02-19", 50000),
                                        (1010, 4, "Oil",   "2026-02-25", 75000),
                                            (1011, 5, "Rice",  "2026-03-02", 85000),
                                                (1012, 2, "Beans", "2026-03-09", 55000),
                                                    (1013, 1, "Oil",   "2026-03-15", 65000),
                                                        (1014, 4, "Rice",  "2026-03-21", 120000),
                                                            (1015, 5, "Beans", "2026-03-28", 70000)
                                                            ])

In [ ]:
import pandas as pd

In [ ]:
pd.read_sql_query("""
SELECT *
FROM orders;
""", conn)

    order_id  customer_id product  order_date  revenue
0       1001            1    Rice  2026-01-05    50000
1       1002            2   Beans  2026-01-07    30000
2       1003            1     Oil  2026-01-12    80000
3       1004            3    Rice  2026-01-18    70000
4       1005            2    Rice  2026-01-22    60000
5       1006            4   Beans  2026-02-03    90000
6       1007            5     Oil  2026-02-08    40000
7       1008            1    Rice  2026-02-14   100000
8       1009            3   Beans  2026-02-19    50000
9       1010            4     Oil  2026-02-25    75000
10      1011            5    Rice  2026-03-02    85000
11      1012            2   Beans  2026-03-09    55000
12      1013            1     Oil  2026-03-15    65000
13      1014            4    Rice  2026-03-21   120000
14      1015            5   Beans  2026-03-28    70000

In [ ]:
pd.read_sql_query("""
SELECT
    order_id,
        customer_id,
            product,
                revenue
                FROM orders
                WHERE revenue > 70000
                ORDER BY revenue DESC;
                """, conn)

   order_id  customer_id product  revenue
0      1014            4    Rice   120000
1      1008            1    Rice   100000
2      1006            4   Beans    90000
3      1011            5    Rice    85000
4      1003            1     Oil    80000
5      1010            4     Oil    75000

In [ ]:
pd.read_sql_query("""
SELECT
    SUM(revenue) AS total_revenue
    FROM orders
    WHERE revenue > 70000;
    """, conn)

   total_revenue
0         550000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        orders.product,
            orders.revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                WHERE orders.revenue > 70000
                ORDER BY orders.revenue DESC;
                """, conn)

  customer_name product  revenue
0         Emeka    Rice   120000
1           Ada    Rice   100000
2         Emeka   Beans    90000
3        Fatima    Rice    85000
4           Ada     Oil    80000
5         Emeka     Oil    75000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            WHERE orders.revenue > 70000
            GROUP BY customers.customer_name;
            """, conn)

  customer_name  total_revenue
0           Ada         180000
1         Emeka         285000
2        Fatima          85000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            WHERE orders.revenue > 70000
            GROUP BY customers.customer_name
            ORDER BY total_revenue DESC;
            """, conn)

  customer_name  total_revenue
0         Emeka         285000
1           Ada         180000
2        Fatima          85000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            WHERE orders.revenue > 70000
            GROUP BY customers.customer_name
            HAVING SUM(orders.revenue) > 100000
            ORDER BY total_revenue DESC;
            """, conn)

  customer_name  total_revenue
0         Emeka         285000
1           Ada         180000

In [ ]:
pd.read_sql_query("""
SELECT
customers.customer_name,
AVG(orders.revenue) AS average_revenue
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_name;
""", conn)

  customer_name  average_revenue
0           Ada     73750.000000
1          Bola     48333.333333
2       Chinedu     60000.000000
3         Emeka     95000.000000
4        Fatima     65000.000000

In [ ]:
pd.read_sql_query("""
SELECT
customers.customer_name,
AVG(orders.revenue) AS average_revenue
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_name
ORDER BY average_revenue DESC;
""", conn)

  customer_name  average_revenue
0         Emeka     95000.000000
1           Ada     73750.000000
2        Fatima     65000.000000
3       Chinedu     60000.000000
4          Bola     48333.333333

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        AVG(orders.revenue) AS average_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.customer_name
            HAVING AVG(orders.revenue) > 60000
            ORDER BY average_revenue DESC;
            """, conn)

  customer_name  average_revenue
0         Emeka          95000.0
1           Ada          73750.0
2        Fatima          65000.0

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        MAX(orders.revenue) AS highest_order
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.customer_name;
            """, conn)

  customer_name  highest_order
0           Ada         100000
1          Bola          60000
2       Chinedu          70000
3         Emeka         120000
4        Fatima          85000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        MAX(orders.revenue) AS highest_order
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.customer_name
            HAVING MAX(orders.revenue) > 70000
            ORDER BY highest_order DESC;
            """, conn)

  customer_name  highest_order
0         Emeka         120000
1           Ada         100000
2        Fatima          85000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.customer_name
            HAVING SUM(orders.revenue) > 200000
            ORDER BY total_revenue DESC;
            """, conn)

  customer_name  total_revenue
0           Ada         295000
1         Emeka         285000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.customer_name
            ORDER BY total_revenue ASC
            LIMIT 1;
            """, conn)

  customer_name  total_revenue
0       Chinedu         120000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.customer_name
            ORDER BY total_revenue DESC
            LIMIT 1 OFFSET 1;
            """, conn)

  customer_name  total_revenue
0         Emeka         285000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY customers.customer_name
                ORDER BY total_revenue DESC;
                """, conn)

  customer_name  total_orders  total_revenue
0           Ada             4         295000
1         Emeka             3         285000
2        Fatima             3         195000
3          Bola             3         145000
4       Chinedu             2         120000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY customers.customer_name
                HAVING COUNT(orders.order_id) >= 3
                   AND SUM(orders.revenue) > 180000
                   ORDER BY total_revenue DESC;
                   """, conn)

  customer_name  total_orders  total_revenue
0           Ada             4         295000
1         Emeka             3         285000
2        Fatima             3         195000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue,
            CASE
                    WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                            WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                    ELSE 'Low'
                                        END AS customer_category
                                        FROM orders
                                        INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                            GROUP BY customers.customer_name
                                            ORDER BY total_revenue DESC;
                                            """, conn)

  customer_name  total_revenue customer_category
0           Ada         295000              High
1         Emeka         285000              High
2        Fatima         195000            Medium
3          Bola         145000               Low
4       Chinedu         120000               Low

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                                                ELSE 'Low'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    COUNT(*) AS customer_count
                                                                                                    FROM customer_categories
                                                                                                    GROUP BY customer_category
                                                                                                    ORDER BY customer_count DESC;
                                                                                                    """, conn)

  customer_category  customer_count
0               Low               2
1              High               2
2            Medium               1

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                                                ELSE 'Low'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            ),
                                                                                            category_counts AS (
                                                                                                SELECT
                                                                                                        customer_category,
                                                                                                                COUNT(*) AS customer_count
                                                                                                                    FROM customer_categories
                                                                                                                        GROUP BY customer_category
                                                                                                                        )
                                                                                                                        SELECT
                                                                                                                            customer_category,
                                                                                                                                customer_count,
                                                                                                                                    ROUND(
                                                                                                                                            customer_count * 100.0 /
                                                                                                                                                    (SELECT COUNT(*) FROM customer_categories),
                                                                                                                                                            2
                                                                                                                                                                ) AS percentage
                                                                                                                                                                FROM category_counts
                                                                                                                                                                ORDER BY percentage DESC;
                                                                                                                                                                """, conn)

  customer_category  customer_count  percentage
0              High               2        40.0
1               Low               2        40.0
2            Medium               1        20.0

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                                                ELSE 'Low'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    SUM(total_revenue) AS category_revenue
                                                                                                    FROM customer_categories
                                                                                                    GROUP BY customer_category
                                                                                                    ORDER BY category_revenue DESC;
                                                                                                    """, conn)

  customer_category  category_revenue
0              High            580000
1               Low            265000
2            Medium            195000

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                                                ELSE 'Low'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    AVG(total_revenue) AS average_revenue
                                                                                                    FROM customer_categories
                                                                                                    GROUP BY customer_category
                                                                                                    ORDER BY average_revenue DESC;
                                                                                                    """, conn)

  customer_category  average_revenue
0              High         290000.0
1            Medium         195000.0
2               Low         132500.0

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                                                ELSE 'Low'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    COUNT(*) AS customer_count,
                                                                                                        SUM(total_revenue) AS category_revenue,
                                                                                                            AVG(total_revenue) AS average_revenue
                                                                                                            FROM customer_categories
                                                                                                            GROUP BY customer_category
                                                                                                            ORDER BY category_revenue DESC;
                                                                                                            """, conn)

  customer_category  customer_count  category_revenue  average_revenue
0              High               2            580000         290000.0
1               Low               2            265000         132500.0
2            Medium               1            195000         195000.0

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium'
                                                                ELSE 'Low'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            ),
                                                                                            category_revenue AS (
                                                                                                SELECT
                                                                                                        customer_category,
                                                                                                                SUM(total_revenue) AS category_revenue
                                                                                                                    FROM customer_categories
                                                                                                                        GROUP BY customer_category
                                                                                                                        )
                                                                                                                        SELECT
                                                                                                                            customer_category,
                                                                                                                                category_revenue,
                                                                                                                                    ROUND(
                                                                                                                                            category_revenue * 100.0 /
                                                                                                                                                    (SELECT SUM(category_revenue) FROM category_revenue),
                                                                                                                                                            2
                                                                                                                                                                ) AS revenue_percentage
                                                                                                                                                                FROM category_revenue
                                                                                                                                                                ORDER BY revenue_percentage DESC;
                                                                                                                                                                """, conn)

  customer_category  category_revenue  revenue_percentage
0              High            580000               55.77
1               Low            265000               25.48
2            Medium            195000               18.75

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        COUNT(order_id) AS total_orders,
            SUM(revenue) AS total_revenue,
                AVG(revenue) AS average_order_value
                FROM orders
                GROUP BY product
                ORDER BY total_revenue DESC;
                """, conn)

  product  total_orders  total_revenue  average_order_value
0    Rice             6         485000         80833.333333
1   Beans             5         295000         59000.000000
2     Oil             4         260000         65000.000000

In [ ]:
pd.read_sql_query("""
WITH product_revenue AS (
    SELECT
            product,
                    SUM(revenue) AS total_revenue
                        FROM orders
                            GROUP BY product
                            )
                            SELECT
                                product,
                                    total_revenue,
                                        ROUND(
                                                total_revenue * 100.0 /
                                                        (SELECT SUM(total_revenue) FROM product_revenue),
                                                                2
                                                                    ) AS revenue_percentage
                                                                    FROM product_revenue
                                                                    ORDER BY revenue_percentage DESC;
                                                                    """, conn)

  product  total_revenue  revenue_percentage
0    Rice         485000               46.63
1   Beans         295000               28.37
2     Oil         260000               25.00

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        MAX(revenue) AS highest_order
        FROM orders
        GROUP BY product
        ORDER BY highest_order DESC;
        """, conn)

  product  highest_order
0    Rice         120000
1   Beans          90000
2     Oil          80000

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        COUNT(order_id) AS total_orders
        FROM orders
        GROUP BY product
        ORDER BY total_orders DESC;
        """, conn)

  product  total_orders
0    Rice             6
1   Beans             5
2     Oil             4

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        COUNT(order_id) AS total_orders,
            SUM(revenue) AS total_revenue
            FROM orders
            GROUP BY product
            HAVING COUNT(order_id) >= 5
               AND SUM(revenue) > 300000
               ORDER BY total_revenue DESC;
               """, conn)

  product  total_orders  total_revenue
0    Rice             6         485000

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        COUNT(order_id) AS total_orders,
            AVG(revenue) AS average_order_value
            FROM orders
            GROUP BY product
            HAVING AVG(revenue) > 60000
            ORDER BY average_order_value DESC;
            """, conn)

  product  total_orders  average_order_value
0    Rice             6         80833.333333
1     Oil             4         65000.000000

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        COUNT(order_id) AS total_orders,
            SUM(revenue) AS total_revenue,
                AVG(revenue) AS average_order_value
                FROM orders
                GROUP BY product
                HAVING COUNT(order_id) >= 5
                   AND SUM(revenue) > 300000
                      AND AVG(revenue) > 60000
                      ORDER BY total_revenue DESC,
                               average_order_value DESC;
                               """, conn)

  product  total_orders  total_revenue  average_order_value
0    Rice             6         485000         80833.333333

In [ ]:
pd.read_sql_query("""
SELECT
    strftime('%Y-%m', order_date) AS month,
        SUM(revenue) AS total_revenue
        FROM orders
        GROUP BY strftime('%Y-%m', order_date)
        ORDER BY month;
        """, conn)

     month  total_revenue
0  2026-01         290000
1  2026-02         355000
2  2026-03         395000

In [ ]:
pd.read_sql_query("""
SELECT
    strftime('%Y-%m', order_date) AS month,
        COUNT(order_id) AS total_orders
        FROM orders
        GROUP BY strftime('%Y-%m', order_date)
        ORDER BY month;
        """, conn)

     month  total_orders
0  2026-01             5
1  2026-02             5
2  2026-03             5

In [ ]:
pd.read_sql_query("""
SELECT
    strftime('%Y-%m', order_date) AS month,
        SUM(revenue) AS total_revenue,
            COUNT(order_id) AS total_orders,
                SUM(revenue) * 1.0 / COUNT(order_id) AS average_order_value
                FROM orders
                GROUP BY strftime('%Y-%m', order_date)
                ORDER BY month;
                """, conn)

     month  total_revenue  total_orders  average_order_value
0  2026-01         290000             5              58000.0
1  2026-02         355000             5              71000.0
2  2026-03         395000             5              79000.0

In [ ]:
pd.read_sql_query("""
SELECT
    strftime('%Y-%m', order_date) AS month,
        product,
            SUM(revenue) AS total_revenue
            FROM orders
            GROUP BY
                strftime('%Y-%m', order_date),
                    product
                    ORDER BY
                        month,
                            total_revenue DESC;
                            """, conn)

     month product  total_revenue
0  2026-01    Rice         180000
1  2026-01     Oil          80000
2  2026-01   Beans          30000
3  2026-02   Beans         140000
4  2026-02     Oil         115000
5  2026-02    Rice         100000
6  2026-03    Rice         205000
7  2026-03   Beans         125000
8  2026-03     Oil          65000

In [ ]:
pd.read_sql_query("""
WITH monthly_product_revenue AS (
    SELECT
            strftime('%Y-%m', order_date) AS month,
                    product,
                            SUM(revenue) AS total_revenue
                                FROM orders
                                    GROUP BY
                                            strftime('%Y-%m', order_date),
                                                    product
                                                    )
                                                    SELECT
                                                        month,
                                                            product,
                                                                total_revenue,
                                                                    ROW_NUMBER() OVER (
                                                                            PARTITION BY month
                                                                                    ORDER BY total_revenue DESC
                                                                                        ) AS product_rank
                                                                                        FROM monthly_product_revenue
                                                                                        ORDER BY month, product_rank;
                                                                                        """, conn)

     month product  total_revenue  product_rank
0  2026-01    Rice         180000             1
1  2026-01     Oil          80000             2
2  2026-01   Beans          30000             3
3  2026-02   Beans         140000             1
4  2026-02     Oil         115000             2
5  2026-02    Rice         100000             3
6  2026-03    Rice         205000             1
7  2026-03   Beans         125000             2
8  2026-03     Oil          65000             3

In [ ]:
pd.read_sql_query("""
WITH monthly_product_revenue AS (
    SELECT
            strftime('%Y-%m', order_date) AS month,
                    product,
                            SUM(revenue) AS total_revenue
                                FROM orders
                                    GROUP BY
                                            strftime('%Y-%m', order_date),
                                                    product
                                                    ),
                                                    ranked_products AS (
                                                        SELECT
                                                                month,
                                                                        product,
                                                                                total_revenue,
                                                                                        ROW_NUMBER() OVER (
                                                                                                    PARTITION BY month
                                                                                                                ORDER BY total_revenue DESC
                                                                                                                        ) AS product_rank
                                                                                                                            FROM monthly_product_revenue
                                                                                                                            )
                                                                                                                            SELECT
                                                                                                                                month,
                                                                                                                                    product,
                                                                                                                                        total_revenue
                                                                                                                                        FROM ranked_products
                                                                                                                                        WHERE product_rank = 1
                                                                                                                                        ORDER BY month;
                                                                                                                                        """, conn)

     month product  total_revenue
0  2026-01    Rice         180000
1  2026-02   Beans         140000
2  2026-03    Rice         205000

In [ ]:
pd.read_sql_query("""
SELECT
    strftime('%Y-%m', orders.order_date) AS month,
        customers.customer_name,
            SUM(orders.revenue) AS total_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY
                    strftime('%Y-%m', orders.order_date),
                        customers.customer_name
                        ORDER BY month, total_revenue DESC;
                        """, conn)

      month customer_name  total_revenue
0   2026-01           Ada         130000
1   2026-01          Bola          90000
2   2026-01       Chinedu          70000
3   2026-02         Emeka         165000
4   2026-02           Ada         100000
5   2026-02       Chinedu          50000
6   2026-02        Fatima          40000
7   2026-03        Fatima         155000
8   2026-03         Emeka         120000
9   2026-03           Ada          65000
10  2026-03          Bola          55000

In [ ]:
pd.read_sql_query("""
WITH monthly_customer_revenue AS (
    SELECT
            strftime('%Y-%m', orders.order_date) AS month,
                    customers.customer_name,
                            SUM(orders.revenue) AS total_revenue
                                FROM orders
                                    INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                                GROUP BY
                                                        strftime('%Y-%m', orders.order_date),
                                                                customers.customer_name
                                                                ),
                                                                ranked_customers AS (
                                                                    SELECT
                                                                            month,
                                                                                    customer_name,
                                                                                            total_revenue,
                                                                                                    ROW_NUMBER() OVER (
                                                                                                                PARTITION BY month
                                                                                                                            ORDER BY total_revenue DESC
                                                                                                                                    ) AS customer_rank
                                                                                                                                        FROM monthly_customer_revenue
                                                                                                                                        )
                                                                                                                                        SELECT
                                                                                                                                            month,
                                                                                                                                                customer_name,
                                                                                                                                                    total_revenue
                                                                                                                                                    FROM ranked_customers
                                                                                                                                                    WHERE customer_rank = 1
                                                                                                                                                    ORDER BY month;
                                                                                                                                                    """, conn)

     month customer_name  total_revenue
0  2026-01           Ada         130000
1  2026-02         Emeka         165000
2  2026-03        Fatima         155000

In [ ]:
pd.read_sql_query("""
SELECT
    strftime('%Y-%m', order_date) AS month,
        SUM(revenue) AS total_revenue
        FROM orders
        GROUP BY strftime('%Y-%m', order_date)
        ORDER BY month;
        """, conn)

     month  total_revenue
0  2026-01         290000
1  2026-02         355000
2  2026-03         395000

In [ ]:
pd.read_sql_query("""
WITH monthly_customer_revenue AS (
    SELECT
            strftime('%Y-%m', orders.order_date) AS month,
                    customers.customer_name,
                            SUM(orders.revenue) AS customer_revenue
                                FROM orders
                                    INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                                GROUP BY
                                                        strftime('%Y-%m', orders.order_date),
                                                                customers.customer_name
                                                                ),
                                                                ranked_customers AS (
                                                                    SELECT
                                                                            month,
                                                                                    customer_name,
                                                                                            customer_revenue,
                                                                                                    ROW_NUMBER() OVER (
                                                                                                                PARTITION BY month
                                                                                                                            ORDER BY customer_revenue DESC
                                                                                                                                    ) AS customer_rank
                                                                                                                                        FROM monthly_customer_revenue
                                                                                                                                        ),
                                                                                                                                        top_customers AS (
                                                                                                                                            SELECT
                                                                                                                                                    month,
                                                                                                                                                            customer_name,
                                                                                                                                                                    customer_revenue
                                                                                                                                                                        FROM ranked_customers
                                                                                                                                                                            WHERE customer_rank = 1
                                                                                                                                                                            ),
                                                                                                                                                                            monthly_totals AS (
                                                                                                                                                                                SELECT
                                                                                                                                                                                        strftime('%Y-%m', order_date) AS month,
                                                                                                                                                                                                SUM(revenue) AS total_revenue
                                                                                                                                                                                                    FROM orders
                                                                                                                                                                                                        GROUP BY strftime('%Y-%m', order_date)
                                                                                                                                                                                                        )
                                                                                                                                                                                                        SELECT
                                                                                                                                                                                                            top_customers.month,
                                                                                                                                                                                                                top_customers.customer_name,
                                                                                                                                                                                                                    top_customers.customer_revenue,
                                                                                                                                                                                                                        monthly_totals.total_revenue,
                                                                                                                                                                                                                            ROUND(
                                                                                                                                                                                                                                    top_customers.customer_revenue * 100.0 /
                                                                                                                                                                                                                                            monthly_totals.total_revenue,
                                                                                                                                                                                                                                                    2
                                                                                                                                                                                                                                                        ) AS revenue_percentage
                                                                                                                                                                                                                                                        FROM top_customers
                                                                                                                                                                                                                                                        JOIN monthly_totals
                                                                                                                                                                                                                                                            ON top_customers.month = monthly_totals.month
                                                                                                                                                                                                                                                            ORDER BY top_customers.month;
                                                                                                                                                                                                                                                            """, conn)

     month customer_name  customer_revenue  total_revenue  revenue_percentage
0  2026-01           Ada            130000         290000               44.83
1  2026-02         Emeka            165000         355000               46.48
2  2026-03        Fatima            155000         395000               39.24

In [ ]:
pd.read_sql_query("""
WITH customer_region_revenue AS (
    SELECT
            customers.region,
                    customers.customer_name,
                            SUM(orders.revenue) AS total_revenue
                                FROM orders
                                    INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                                GROUP BY
                                                        customers.region,
                                                                customers.customer_name
                                                                ),
                                                                ranked_customers AS (
                                                                    SELECT
                                                                            region,
                                                                                    customer_name,
                                                                                            total_revenue,
                                                                                                    ROW_NUMBER() OVER (
                                                                                                                PARTITION BY region
                                                                                                                            ORDER BY total_revenue DESC
                                                                                                                                    ) AS customer_rank
                                                                                                                                        FROM customer_region_revenue
                                                                                                                                        )
                                                                                                                                        SELECT
                                                                                                                                            region,
                                                                                                                                                customer_name,
                                                                                                                                                    total_revenue
                                                                                                                                                    FROM ranked_customers
                                                                                                                                                    WHERE customer_rank = 1
                                                                                                                                                    ORDER BY region;
                                                                                                                                                    """, conn)

   region customer_name  total_revenue
0  Ibadan           Ada         295000
1   Lagos        Fatima         195000
2  Osogbo       Chinedu         120000

In [ ]:
pd.read_sql_query("""
WITH customer_region_revenue AS (
    SELECT
            customers.region,
                    customers.customer_name,
                            SUM(orders.revenue) AS customer_revenue
                                FROM orders
                                    INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                                GROUP BY
                                                        customers.region,
                                                                customers.customer_name
                                                                ),
                                                                ranked_customers AS (
                                                                    SELECT
                                                                            region,
                                                                                    customer_name,
                                                                                            customer_revenue,
                                                                                                    ROW_NUMBER() OVER (
                                                                                                                PARTITION BY region
                                                                                                                            ORDER BY customer_revenue DESC
                                                                                                                                    ) AS customer_rank
                                                                                                                                        FROM customer_region_revenue
                                                                                                                                        ),
                                                                                                                                        top_customers AS (
                                                                                                                                            SELECT
                                                                                                                                                    region,
                                                                                                                                                            customer_name,
                                                                                                                                                                    customer_revenue
                                                                                                                                                                        FROM ranked_customers
                                                                                                                                                                            WHERE customer_rank = 1
                                                                                                                                                                            ),
                                                                                                                                                                            regional_totals AS (
                                                                                                                                                                                SELECT
                                                                                                                                                                                        customers.region,
                                                                                                                                                                                                SUM(orders.revenue) AS regional_revenue
                                                                                                                                                                                                    FROM orders
                                                                                                                                                                                                        INNER JOIN customers
                                                                                                                                                                                                                ON orders.customer_id = customers.customer_id
                                                                                                                                                                                                                    GROUP BY customers.region
                                                                                                                                                                                                                    )
                                                                                                                                                                                                                    SELECT
                                                                                                                                                                                                                        top_customers.region,
                                                                                                                                                                                                                            top_customers.customer_name,
                                                                                                                                                                                                                                top_customers.customer_revenue,
                                                                                                                                                                                                                                    regional_totals.regional_revenue,
                                                                                                                                                                                                                                        ROUND(
                                                                                                                                                                                                                                                top_customers.customer_revenue * 100.0 /
                                                                                                                                                                                                                                                        regional_totals.regional_revenue,
                                                                                                                                                                                                                                                                2
                                                                                                                                                                                                                                                                    ) AS revenue_percentage
                                                                                                                                                                                                                                                                    FROM top_customers
                                                                                                                                                                                                                                                                    INNER JOIN regional_totals
                                                                                                                                                                                                                                                                        ON top_customers.region = regional_totals.region
                                                                                                                                                                                                                                                                        ORDER BY top_customers.region;
                                                                                                                                                                                                                                                                        """, conn)

,region,customer_name,customer_revenue,regional_revenue,revenue_percentage
0,Ibadan,Ada,295000,580000,50.86
1,Lagos,Fatima,195000,340000,57.35
2,Osogbo,Chinedu,120000,120000,100.00

In [ ]:
pd.read_sql_query("""
SELECT
    customers.region,
        SUM(orders.revenue) AS regional_revenue
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY customers.region
            ORDER BY regional_revenue DESC;
            """, conn)

   region  regional_revenue
0  Ibadan            580000
1   Lagos            340000
2  Osogbo            120000

In [ ]:
pd.read_sql_query("""
WITH regional_totals AS (
    SELECT
            customers.region,
                    SUM(orders.revenue) AS regional_revenue
                        FROM orders
                            INNER JOIN customers
                                    ON orders.customer_id = customers.customer_id
                                        GROUP BY customers.region
                                        )
                                        SELECT
                                            region,
                                                regional_revenue,
                                                    ROUND(
                                                            regional_revenue * 100.0 /
                                                                    (SELECT SUM(revenue) FROM orders),
                                                                            2
                                                                                ) AS revenue_percentage
                                                                                FROM regional_totals
                                                                                ORDER BY regional_revenue DESC;
                                                                                """, conn)

   region  regional_revenue  revenue_percentage
0  Ibadan            580000               55.77
1   Lagos            340000               32.69
2  Osogbo            120000               11.54

In [ ]:
pd.read_sql_query("""
SELECT
    customers.region,
        COUNT(DISTINCT customers.customer_id) AS customer_count,
            SUM(orders.revenue) AS regional_revenue,
                ROUND(
                        SUM(orders.revenue) * 1.0 /
                                COUNT(DISTINCT customers.customer_id),
                                        2
                                            ) AS revenue_per_customer
                                            FROM orders
                                            INNER JOIN customers
                                                ON orders.customer_id = customers.customer_id
                                                GROUP BY customers.region
                                                ORDER BY regional_revenue DESC;
                                                """, conn)

   region  customer_count  regional_revenue  revenue_per_customer
0  Ibadan               2            580000              290000.0
1   Lagos               2            340000              170000.0
2  Osogbo               1            120000              120000.0

In [ ]:
pd.read_sql_query("""
SELECT
    customers.region,
        strftime('%Y-%m', orders.order_date) AS month,
            SUM(orders.revenue) AS monthly_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY
                    customers.region,
                        strftime('%Y-%m', orders.order_date)
                        ORDER BY
                            customers.region,
                                month;
                                """, conn)

   region    month  monthly_revenue
0  Ibadan  2026-01           130000
1  Ibadan  2026-02           265000
2  Ibadan  2026-03           185000
3   Lagos  2026-01            90000
4   Lagos  2026-02            40000
5   Lagos  2026-03           210000
6  Osogbo  2026-01            70000
7  Osogbo  2026-02            50000

In [ ]:
pd.read_sql_query("""
WITH regional_monthly AS (
    SELECT
            customers.region,
                    strftime('%Y-%m', orders.order_date) AS month,
                            SUM(orders.revenue) AS monthly_revenue
                                FROM orders
                                    INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                                GROUP BY
                                                        customers.region,
                                                                strftime('%Y-%m', orders.order_date)
                                                                )
                                                                SELECT
                                                                    region,
                                                                        month,
                                                                            monthly_revenue,
                                                                                LAG(monthly_revenue) OVER (
                                                                                        PARTITION BY region
                                                                                                ORDER BY month
                                                                                                    ) AS previous_month_revenue,
                                                                                                        monthly_revenue -
                                                                                                                LAG(monthly_revenue) OVER (
                                                                                                                            PARTITION BY region
                                                                                                                                        ORDER BY month
                                                                                                                                                ) AS revenue_change
                                                                                                                                                FROM regional_monthly
                                                                                                                                                ORDER BY region, month;
                                                                                                                                                """, conn)

   region    month  monthly_revenue  previous_month_revenue  revenue_change
0  Ibadan  2026-01           130000                     NaN             NaN
1  Ibadan  2026-02           265000                130000.0        135000.0
2  Ibadan  2026-03           185000                265000.0        -80000.0
3   Lagos  2026-01            90000                     NaN             NaN
4   Lagos  2026-02            40000                 90000.0        -50000.0
5   Lagos  2026-03           210000                 40000.0        170000.0
6  Osogbo  2026-01            70000                     NaN             NaN
7  Osogbo  2026-02            50000                 70000.0        -20000.0

In [ ]:
pd.read_sql_query("""
WITH regional_monthly AS (
    SELECT
            customers.region,
                    strftime('%Y-%m', orders.order_date) AS month,
                            SUM(orders.revenue) AS monthly_revenue
                                FROM orders
                                    INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                                GROUP BY
                                                        customers.region,
                                                                strftime('%Y-%m', orders.order_date)
                                                                ),
                                                                regional_changes AS (
                                                                    SELECT
                                                                            region,
                                                                                    month,
                                                                                            monthly_revenue,
                                                                                                    LAG(monthly_revenue) OVER (
                                                                                                                PARTITION BY region
                                                                                                                            ORDER BY month
                                                                                                                                    ) AS previous_month_revenue
                                                                                                                                        FROM regional_monthly
                                                                                                                                        )
                                                                                                                                        SELECT
                                                                                                                                            region,
                                                                                                                                                month,
                                                                                                                                                    monthly_revenue,
                                                                                                                                                        previous_month_revenue,
                                                                                                                                                            ROUND(
                                                                                                                                                                    (monthly_revenue - previous_month_revenue) * 100.0
                                                                                                                                                                            / previous_month_revenue,
                                                                                                                                                                                    2
                                                                                                                                                                                        ) AS percentage_change
                                                                                                                                                                                        FROM regional_changes
                                                                                                                                                                                        ORDER BY region, month;
                                                                                                                                                                                        """, conn)

   region    month  monthly_revenue  previous_month_revenue  percentage_change
0  Ibadan  2026-01           130000                     NaN                NaN
1  Ibadan  2026-02           265000                130000.0             103.85
2  Ibadan  2026-03           185000                265000.0             -30.19
3   Lagos  2026-01            90000                     NaN                NaN
4   Lagos  2026-02            40000                 90000.0             -55.56
5   Lagos  2026-03           210000                 40000.0             425.00
6  Osogbo  2026-01            70000                     NaN                NaN
7  Osogbo  2026-02            50000                 70000.0             -28.57

In [ ]:
pd.read_sql_query("""
SELECT
    customers.region,
        COUNT(DISTINCT customers.customer_id) AS customer_count,
            COUNT(orders.order_id) AS total_orders,
                SUM(orders.revenue) AS regional_revenue,
                    ROUND(
                            SUM(orders.revenue) * 1.0 /
                                    COUNT(DISTINCT customers.customer_id),
                                            2
                                                ) AS revenue_per_customer
                                                FROM orders
                                                INNER JOIN customers
                                                    ON orders.customer_id = customers.customer_id
                                                    GROUP BY customers.region
                                                    ORDER BY regional_revenue DESC;
                                                    """, conn)

,region,customer_count,total_orders,regional_revenue,revenue_per_customer
0,Ibadan,2,7,580000,290000.0
1,Lagos,2,6,340000,170000.0
2,Osogbo,1,2,120000,120000.0

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders
        FROM orders
        INNER JOIN customers
            ON orders.customer_id = customers.customer_id
            GROUP BY
                customers.customer_name
                HAVING COUNT(orders.order_id) > 1
                ORDER BY total_orders DESC;
                """, conn)

  customer_name  total_orders
0           Ada             4
1        Fatima             3
2         Emeka             3
3          Bola             3
4       Chinedu             2

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY customers.customer_name
                ORDER BY total_orders DESC, total_revenue DESC;
                """, conn)

  customer_name  total_orders  total_revenue
0           Ada             4         295000
1         Emeka             3         285000
2        Fatima             3         195000
3          Bola             3         145000
4       Chinedu             2         120000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue,
                ROUND(AVG(orders.revenue), 2) AS average_order_value
                FROM orders
                INNER JOIN customers
                    ON orders.customer_id = customers.customer_id
                    GROUP BY customers.customer_name
                    ORDER BY average_order_value DESC;
                    """, conn)

  customer_name  total_orders  total_revenue  average_order_value
0         Emeka             3         285000             95000.00
1           Ada             4         295000             73750.00
2        Fatima             3         195000             65000.00
3       Chinedu             2         120000             60000.00
4          Bola             3         145000             48333.33

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY customers.customer_name
                HAVING
                    COUNT(orders.order_id) >= 3
                        AND SUM(orders.revenue) > 180000
                        ORDER BY total_revenue DESC;
                        """, conn)

  customer_name  total_orders  total_revenue
0           Ada             4         295000
1         Emeka             3         285000
2        Fatima             3         195000

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        SUM(orders.revenue) AS total_revenue,
            CASE
                    WHEN SUM(orders.revenue) >= 250000 THEN 'High Value'
                            WHEN SUM(orders.revenue) >= 180000 THEN 'Medium Value'
                                    ELSE 'Low Value'
                                        END AS customer_category
                                        FROM orders
                                        INNER JOIN customers
                                            ON orders.customer_id = customers.customer_id
                                            GROUP BY customers.customer_name
                                            ORDER BY total_revenue DESC;
                                            """, conn)

  customer_name  total_revenue customer_category
0           Ada         295000        High Value
1         Emeka         285000        High Value
2        Fatima         195000      Medium Value
3          Bola         145000         Low Value
4       Chinedu         120000         Low Value

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High Value'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium Value'
                                                                ELSE 'Low Value'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    COUNT(*) AS customer_count
                                                                                                    FROM customer_categories
                                                                                                    GROUP BY customer_category
                                                                                                    ORDER BY customer_count DESC;
                                                                                                    """, conn)

  customer_category  customer_count
0         Low Value               2
1        High Value               2
2      Medium Value               1

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High Value'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium Value'
                                                                ELSE 'Low Value'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    COUNT(*) AS customer_count,
                                                                                                        SUM(total_revenue) AS category_revenue
                                                                                                        FROM customer_categories
                                                                                                        GROUP BY customer_category
                                                                                                        ORDER BY category_revenue DESC;
                                                                                                        """, conn)

  customer_category  customer_count  category_revenue
0        High Value               2            580000
1         Low Value               2            265000
2      Medium Value               1            195000

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High Value'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium Value'
                                                                ELSE 'Low Value'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            ),
                                                                                            category_totals AS (
                                                                                                SELECT
                                                                                                        customer_category,
                                                                                                                COUNT(*) AS customer_count,
                                                                                                                        SUM(total_revenue) AS category_revenue
                                                                                                                            FROM customer_categories
                                                                                                                                GROUP BY customer_category
                                                                                                                                )
                                                                                                                                SELECT
                                                                                                                                    customer_category,
                                                                                                                                        customer_count,
                                                                                                                                            category_revenue,
                                                                                                                                                ROUND(
                                                                                                                                                        category_revenue * 100.0 /
                                                                                                                                                                (SELECT SUM(revenue) FROM orders),
                                                                                                                                                                        2
                                                                                                                                                                            ) AS revenue_percentage
                                                                                                                                                                            FROM category_totals
                                                                                                                                                                            ORDER BY category_revenue DESC;
                                                                                                                                                                            """, conn)

  customer_category  customer_count  category_revenue  revenue_percentage
0        High Value               2            580000               55.77
1         Low Value               2            265000               25.48
2      Medium Value               1            195000               18.75

In [ ]:
pd.read_sql_query("""
WITH customer_categories AS (
    SELECT
            customers.customer_name,
                    SUM(orders.revenue) AS total_revenue,
                            CASE
                                        WHEN SUM(orders.revenue) >= 250000 THEN 'High Value'
                                                    WHEN SUM(orders.revenue) >= 180000 THEN 'Medium Value'
                                                                ELSE 'Low Value'
                                                                        END AS customer_category
                                                                            FROM orders
                                                                                INNER JOIN customers
                                                                                        ON orders.customer_id = customers.customer_id
                                                                                            GROUP BY customers.customer_name
                                                                                            )
                                                                                            SELECT
                                                                                                customer_category,
                                                                                                    COUNT(*) AS customer_count,
                                                                                                        SUM(total_revenue) AS category_revenue,
                                                                                                            ROUND(AVG(total_revenue), 2) AS average_revenue_per_customer
                                                                                                            FROM customer_categories
                                                                                                            GROUP BY customer_category
                                                                                                            ORDER BY average_revenue_per_customer DESC;
                                                                                                            """, conn)

,customer_category,customer_count,category_revenue,average_revenue_per_customer
0,High Value,2,580000,290000.0
1,Medium Value,1,195000,195000.0
2,Low Value,2,265000,132500.0

## Database Setup

The analysis was performed using SQLite in a Google Colab environment.

Two relational tables were created:

### Customers Table
Contains customer information:
- Customer ID
- Customer Name
- Region

### Orders Table
Contains transaction information:
- Order ID
- Customer ID
- Product
- Order Date
- Revenue

The `customer_id` field was used to connect the two tables and perform relational analysis using SQL JOINs.

## SQL Practice

The following section contains exploratory SQL queries used to practice filtering, aggregation, grouping, joins, subqueries, CTEs, and window functions before the final business analysis.

These queries demonstrate the development and application of SQL skills throughout the project.

## Final Business Analysis

The following sections present the final business analysis and key findings derived from the SQL queries.

###Customer Analysis

This section analyzes customer purchasing behavior and identifies the highest-value customers based on order frequency, total revenue, and average order value (AOV).

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue,
                ROUND(AVG(orders.revenue), 2) AS average_order_value
                FROM orders
                INNER JOIN customers
                    ON orders.customer_id = customers.customer_id
                    GROUP BY customers.customer_name
                    ORDER BY total_revenue DESC;
                    """, conn)

  customer_name  total_orders  total_revenue  average_order_value
0           Ada             4         295000             73750.00
1         Emeka             3         285000             95000.00
2        Fatima             3         195000             65000.00
3          Bola             3         145000             48333.33
4       Chinedu             2         120000             60000.00

### Customer Performance Insight

Ada generated the highest total revenue at ₦295,000 and also had the highest number of orders with 4 purchases.

Emeka generated ₦285,000 from 3 orders and had the highest average order value at ₦95,000, indicating that Emeka makes fewer but higher-value purchases.

Bola had the lowest average order value at approximately ₦48,333, suggesting an opportunity to increase purchase value through targeted offers or product recommendations.

### High-Value Customers

Customers were classified as high-value when they had at least 3 orders and generated more than ₦180,000 in total revenue.

In [ ]:
pd.read_sql_query("""
SELECT
    customers.customer_name,
        COUNT(orders.order_id) AS total_orders,
            SUM(orders.revenue) AS total_revenue
            FROM orders
            INNER JOIN customers
                ON orders.customer_id = customers.customer_id
                GROUP BY customers.customer_name
                HAVING
                    COUNT(orders.order_id) >= 3
                        AND SUM(orders.revenue) > 180000
                        ORDER BY total_revenue DESC;
                        """, conn)

  customer_name  total_orders  total_revenue
0           Ada             4         295000
1         Emeka             3         285000
2        Fatima             3         195000

### High-Value Customer Insight

Three customers met the high-value criteria: Ada, Emeka, and Fatima.

Together, these customers generated ₦775,000 in revenue, representing approximately 74.5% of the total revenue in the dataset.

This indicates a significant dependence on a small group of customers, making customer retention important while also creating an opportunity to develop Medium Value customers.

###Product Analysis

This section evaluates product performance based on order volume, total revenue, and average order value to identify the strongest products and potential growth opportunities.

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        COUNT(order_id) AS total_orders,
            SUM(revenue) AS total_revenue,
                ROUND(AVG(revenue), 2) AS average_order_value
                FROM orders
                GROUP BY product
                ORDER BY total_revenue DESC;
                """, conn)

  product  total_orders  total_revenue  average_order_value
0    Rice             6         485000             80833.33
1   Beans             5         295000             59000.00
2     Oil             4         260000             65000.00

### Product Performance Insight

Rice was the strongest-performing product, generating ₦485,000 in revenue from 6 orders and recording the highest average order value of approximately ₦80,833.

Beans generated ₦295,000 from 5 orders, while Oil generated ₦260,000 from 4 orders.

Although Oil generated less total revenue than Beans, its average order value was higher at ₦65,000 compared with Beans at ₦59,000. This suggests that Oil may have potential for growth if its order volume can be increased.

Management should maintain Rice's strong performance while exploring strategies to improve the sales volume of Beans and Oil.

In [ ]:
pd.read_sql_query("""
SELECT
    product,
        SUM(revenue) AS total_revenue,
            ROUND(
                    SUM(revenue) * 100.0 /
                            (SELECT SUM(revenue) FROM orders),
                                    2
                                        ) AS revenue_contribution_percent
                                        FROM orders
                                        GROUP BY product
                                        ORDER BY total_revenue DESC;
                                        """, conn)

  product  total_revenue  revenue_contribution_percent
0    Rice         485000                         46.63
1   Beans         295000                         28.37
2     Oil         260000                         25.00

### Product Revenue Contribution Insight

Rice contributed the largest share of total revenue at 46.63%, making it the leading product in the dataset.

Beans contributed 28.37%, while Oil contributed 25.00%.

Although Rice generated almost half of total revenue, the other two products together contributed 53.37%. This shows that the business is not completely dependent on Rice and has opportunities to strengthen Beans and Oil.

Management should maintain Rice's strong performance while developing strategies to increase the revenue contribution of Beans and Oil.

###Monthly Sales Analysis

This section examines monthly revenue performance to identify sales trends and changes in average order value over time.

In [ ]:
pd.read_sql_query("""
SELECT
    SUBSTR(order_date, 1, 7) AS month,
        COUNT(order_id) AS total_orders,
            SUM(revenue) AS total_revenue,
                ROUND(AVG(revenue), 2) AS average_order_value
                FROM orders
                GROUP BY SUBSTR(order_date, 1, 7)
                ORDER BY month;
                """, conn)

     month  total_orders  total_revenue  average_order_value
0  2026-01             5         290000              58000.0
1  2026-02             5         355000              71000.0
2  2026-03             5         395000              79000.0

### Monthly Sales Insight

Monthly revenue increased consistently from ₦290,000 in January to ₦355,000 in February and ₦395,000 in March.

The number of orders remained constant at 5 orders each month, while average order value increased from ₦58,000 in January to ₦71,000 in February and ₦79,000 in March.

This indicates that revenue growth was driven by higher-value purchases rather than an increase in order volume.

Management should investigate the factors behind the increase in average order value and consider strategies that encourage customers to make larger purchases.

###Regional Analysis

This section evaluates revenue performance across regions to identify regional strengths, customer concentration, and potential growth opportunities.

In [ ]:
pd.read_sql_query("""
SELECT
    customers.region,
        COUNT(DISTINCT customers.customer_id) AS total_customers,
            COUNT(orders.order_id) AS total_orders,
                SUM(orders.revenue) AS total_revenue,
                    ROUND(AVG(orders.revenue), 2) AS average_order_value
                    FROM orders
                    INNER JOIN customers
                        ON orders.customer_id = customers.customer_id
                        GROUP BY customers.region
                        ORDER BY total_revenue DESC;
                        """, conn)

   region  total_customers  total_orders  total_revenue  average_order_value
0  Ibadan                2             7         580000             82857.14
1   Lagos                2             6         340000             56666.67
2  Osogbo                1             2         120000             60000.00

### Regional Performance Insight

Ibadan generated the highest revenue at ₦580,000 from 7 orders and 2 customers, with the highest average order value of approximately ₦82,857.

Lagos generated ₦340,000 from 6 orders and 2 customers, while Osogbo generated ₦120,000 from 2 orders and 1 customer.

Ibadan is currently the strongest-performing region in terms of revenue, order volume, and average order value. However, the highest-revenue region is not automatically the best growth opportunity.

Management should investigate customer acquisition, repeat purchasing, and revenue trends in each region before deciding where to focus expansion efforts.

###Customer Behavior & Segmentation

This section segments customers based on their order frequency and total revenue to identify high-value customers and potential growth opportunities.

In [ ]:
pd.read_sql_query("""
SELECT
    customer_name,
        COUNT(order_id) AS total_orders,
            SUM(revenue) AS total_revenue,
                CASE
                        WHEN SUM(revenue) >= 250000 THEN 'High Value'
                                WHEN SUM(revenue) >= 180000 THEN 'Medium Value'
                                        ELSE 'Low Value'
                                            END AS customer_segment
                                            FROM orders
                                            INNER JOIN customers
                                                ON orders.customer_id = customers.customer_id
                                                GROUP BY customer_name
                                                ORDER BY total_revenue DESC;
                                                """, conn)

  customer_name  total_orders  total_revenue customer_segment
0           Ada             4         295000       High Value
1         Emeka             3         285000       High Value
2        Fatima             3         195000     Medium Value
3          Bola             3         145000        Low Value
4       Chinedu             2         120000        Low Value

### Customer Segmentation Insight

Two customers, Ada and Emeka, were classified as High Value, generating ₦580,000 in combined revenue.

Fatima was classified as Medium Value with ₦195,000 in revenue, while Bola and Chinedu were classified as Low Value.

Although High Value customers represent only 40% of the customer base, they generated approximately 55.77% of total revenue in the dataset.

This indicates that high-value customers are particularly important to the business. Management should prioritize retaining these customers while developing strategies to increase the value of Medium and Low Value customers.

###Key Business Insights

1. **Customer concentration:** High Value customers represent 40% of the customer base but contribute approximately 55.77% of total revenue. Customer retention is therefore important.

2. **Product performance:** Rice is the leading product, generating ₦485,000 and contributing 46.63% of total revenue. Beans and Oil provide additional revenue opportunities.

3. **Revenue growth:** Monthly revenue increased from ₦290,000 in January to ₦395,000 in March, while the number of orders remained constant at 5 per month. Growth was therefore driven by higher average order values.

4. **Regional performance:** Ibadan generated the highest revenue at ₦580,000 and also had the highest average order value. However, revenue alone should not determine where future expansion should be focused.

5. **Growth opportunities:** Management can protect the performance of Rice and High Value customers while developing strategies to increase the purchasing value of Medium and Low Value customers and improve Beans and Oil sales.

###Business Recommendations

1. **Retain High Value customers:** Develop customer retention strategies such as personalized offers, loyalty incentives, and follow-up communication for high-value customers.

2. **Increase customer value:** Encourage Medium and Low Value customers to make larger or more frequent purchases through targeted promotions, bundles, and product recommendations.

3. **Maintain Rice's performance:** Rice is the strongest product, so management should protect its current performance while monitoring demand and inventory.

4. **Improve Beans and Oil sales:** Investigate why Beans and Oil generate less revenue than Rice and identify opportunities to increase their order volume and revenue contribution.

5. **Increase order value:** Since monthly revenue increased while order volume remained constant, management should continue strategies that encourage larger purchases.

6. **Evaluate regional opportunities:** Ibadan currently performs best, but management should examine customer acquisition, repeat purchases, and regional trends before making expansion decisions.

###Limitations

- The dataset contains only 15 orders and 5 customers, so the findings may not represent long-term business performance.
- The analysis covers only January to March 2026, which limits the ability to identify seasonal patterns.
- The dataset does not include product costs or profit information, so product profitability cannot be evaluated.
- Regional performance is based on a small number of customers, so regional comparisons should be interpreted with caution.
- Customer behavior may change as more transactions are collected.

###Conclusion

The SQL analysis provided useful insights into customer behavior, product performance, regional revenue, and monthly sales trends.

The business generated ₦1.04 million in total revenue from 15 orders. Rice was the leading product, while Ada and Emeka were the highest-value customers under the customer segmentation criteria.

Monthly revenue increased from January to March without an increase in order volume, indicating that higher average order values were a major driver of growth.

Overall, the analysis shows that the business should protect its strongest customers and products while developing strategies to increase customer value, improve the performance of other products, and identify sustainable regional growth opportunities.